# Generated by Django 2.2.5 on 2019-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190917_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('marketStartTime', models.CharField(max_length=50)),
                ('marketId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marketStatus', models.CharField(max_length=50)),
                ('inPlay', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('selectionId', models.CharField(max_length=50)),
                ('runnerName', models.CharField(max_length=50)),
                ('runnerStatus', models.CharField(max_length=50)),
                ('back', models.FloatField(max_length=50)),
                ('lay', models.FloatField(max_length=50)),
            ],
        ),
    ]
