# Generated by Django 2.1.7 on 2019-10-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_racedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('marketStartTime', models.CharField(max_length=50)),
                ('marketId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marketStatus', models.CharField(max_length=50)),
                ('inPlay', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('back', models.FloatField(max_length=50)),
                ('lay', models.FloatField(max_length=50)),
            ],
            options={
                'ordering': ('marketStartTime',),
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectionId', models.CharField(max_length=50)),
                ('runnerName', models.CharField(max_length=50)),
                ('runnerStatus', models.CharField(max_length=50)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Market')),
            ],
        ),
        migrations.DeleteModel(
            name='RaceData',
        ),
    ]
