# Generated by Django 2.1.7 on 2019-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191001_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='id',
        ),
        migrations.AlterField(
            model_name='runner',
            name='selectionId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
