# Generated by Django 2.2.6 on 2019-10-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_sportsapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsapi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
