# Generated by Django 2.2.6 on 2019-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191010_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=400)),
                ('params', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=200)),
                ('marketDictionary', models.CharField(max_length=10)),
                ('bookRequestList', models.CharField(max_length=10)),
                ('runnerDictionary', models.CharField(max_length=10)),
            ],
        ),
    ]
