# Generated by Django 2.2.6 on 2019-10-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together={('market', 'selectionId')},
        ),
    ]
