# Generated by Django 2.2.6 on 2019-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191030_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDictionaryM',
            fields=[
                ('market_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('market_obj', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RunnerDictionaryM',
            fields=[
                ('runner_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('runner_obj', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='bookRequestList',
        ),
        migrations.RemoveField(
            model_name='form',
            name='marketDictionary',
        ),
        migrations.RemoveField(
            model_name='form',
            name='runnerDictionary',
        ),
    ]
