# Generated by Django 2.2.6 on 2019-10-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191031_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdictionarym',
            name='market_obj',
        ),
        migrations.RemoveField(
            model_name='runnerdictionarym',
            name='runner_obj',
        ),
        migrations.AddField(
            model_name='marketdictionarym',
            name='market_inPlay',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marketdictionarym',
            name='market_removed',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marketdictionarym',
            name='market_status',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='runnerdictionarym',
            name='market_backPrice',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='runnerdictionarym',
            name='market_layPrice',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='runnerdictionarym',
            name='market_status',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
