# Generated by Django 2.2.6 on 2019-10-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191031_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runnerdictionarym',
            old_name='market_backPrice',
            new_name='runner_backPrice',
        ),
        migrations.RenameField(
            model_name='runnerdictionarym',
            old_name='market_layPrice',
            new_name='runner_layPrice',
        ),
        migrations.RenameField(
            model_name='runnerdictionarym',
            old_name='market_status',
            new_name='runner_status',
        ),
    ]
